# Generated by Django 3.2 on 2021-08-13 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '1. Published'), (2, '2. Preparing to publish'), (3, '3. Accepted'), (4, '4. Posted by publisher'), (5, '5. Draft'), (6, '6. Rejected'), (7, '7. Deleted by publisher')], db_index=True, default=4)),
                ('reason_for_rejection', models.TextField(blank=True)),
                ('apex_language', models.CharField(max_length=20)),
                ('en_text', models.TextField(blank=True, verbose_name='Text in English')),
                ('zh_hans_text', models.TextField(blank=True, verbose_name='Text in Chinese Simplified')),
                ('zh_hant_text', models.TextField(blank=True, verbose_name='Text in Chinese Traditional')),
                ('es_text', models.TextField(blank=True, verbose_name='Text in Spanish')),
                ('ar_text', models.TextField(blank=True, verbose_name='Text in Arabic')),
                ('fr_text', models.TextField(blank=True, verbose_name='Text in French')),
                ('ru_text', models.TextField(blank=True, verbose_name='Text in Russian')),
                ('apex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='opinion.opinion')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topic.topic')),
            ],
            options={
                'db_table': 'opinion',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='OpinionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='%Y-%m-%d/')),
                ('original_label', models.CharField(default='', max_length=200)),
                ('md5', models.CharField(db_index=True, default='', max_length=32)),
                ('size', models.PositiveIntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='opinion.opinion')),
            ],
            options={
                'db_table': 'opinion_attachment',
            },
        ),
    ]
