# Generated by Django 3.2 on 2021-06-09 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('published', models.BooleanField(default=False)),
                ('en_name', models.CharField(max_length=200, verbose_name='Name in English')),
                ('zh_hans_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Chinese Simplified')),
                ('zh_hant_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Chinese Traditional')),
                ('es_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Spanish')),
                ('ar_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Arabic')),
                ('fr_name', models.CharField(blank=True, max_length=200, verbose_name='Name in French')),
                ('ru_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Russian')),
                ('en_description', models.CharField(max_length=500, verbose_name='Description in English')),
                ('zh_hans_description', models.CharField(blank=True, max_length=500, verbose_name='Description in Chinese Simplified')),
                ('zh_hant_description', models.CharField(blank=True, max_length=500, verbose_name='Description in Chinese Traditional')),
                ('es_description', models.CharField(blank=True, max_length=500, verbose_name='Description in Spanish')),
                ('ar_description', models.CharField(blank=True, max_length=500, verbose_name='Description in Arabic')),
                ('fr_description', models.CharField(blank=True, max_length=500, verbose_name='Description in French')),
                ('ru_description', models.CharField(blank=True, max_length=500, verbose_name='Description in Russian')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.category')),
            ],
            options={
                'db_table': 'topic',
                'ordering': ('-updated', '-pk'),
            },
        ),
    ]
