# Generated by Django 3.2 on 2021-08-23 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('md5', models.CharField(default='', max_length=32)),
                ('size', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'article_media',
                'ordering': ('image',),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.BooleanField(default=False)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '1. Published'), (2, '2. Preparing to publish'), (3, '3. Draft')], default=3)),
                ('page_home', models.BooleanField(default=False)),
                ('en_content', models.TextField(blank=True, verbose_name='Content in English')),
                ('zh_hans_content', models.TextField(blank=True, verbose_name='Content in Chinese')),
                ('es_content', models.TextField(blank=True, verbose_name='Content in Spanish')),
                ('ar_content', models.TextField(blank=True, verbose_name='Content in Arabic')),
                ('fr_content', models.TextField(blank=True, verbose_name='Content in French')),
                ('ru_content', models.TextField(blank=True, verbose_name='Content in Russian')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='topic.topic')),
            ],
            options={
                'db_table': 'article',
                'ordering': ('mobile', 'status', '-page_home', 'category', 'topic', 'pk'),
            },
        ),
    ]
