# Generated by Django 3.2 on 2021-06-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_by_this', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('slug', models.SlugField()),
                ('show_in_top_nav', models.BooleanField(default=False)),
                ('en_name', models.CharField(max_length=200, verbose_name='Name in English')),
                ('zh_hans_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Chinese Simplified')),
                ('zh_hant_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Chinese Traditional')),
                ('es_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Spanish')),
                ('ar_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Arabic')),
                ('fr_name', models.CharField(blank=True, max_length=200, verbose_name='Name in French')),
                ('ru_name', models.CharField(blank=True, max_length=200, verbose_name='Name in Russian')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='category.category', verbose_name='Root category')),
            ],
            options={
                'db_table': 'category',
                'ordering': ('order_by_this', 'pk'),
            },
        ),
    ]
